apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app-deployment
  labels:
    app: gemini-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels:
        app: gemini-app
    spec:
      containers:
      - name: gemini-app-container
        image: ankurlkw/gemini-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: GEMINI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-app-service
spec:
  # type: LoadBalancer
  selector:
    app: gemini-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemini-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gemini.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gemini-app-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-app-configmap
data:
  log_level: "Info"
