apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app-deployment
  labels:
    app: gemini-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels:
        app: gemini-app
    spec:
      containers:
      - name: gemini-app-container
        image: ankurlkw/gemini-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: GEMINI_API_KEY
