apiVersion: v1
kind: Pod
metadata:
  name: gemini-app-pod
  labels:
    app: gemini-app
spec:
  containers:
  - name: gemini-app-container
    image: ankurlkw/gemini-app:latest
    ports:
    - containerPort: 3000
    env:
    - name: GEMINI_API_KEY
      valueFrom:
        secretKeyRef:
          name: gemini-api-key
          key: GEMINI_API_KEY
